version: '3.1'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - sql-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  goapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_SERVER_ADDRESS: ${MYSQL_SERVER_ADDRESS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy

volumes:
  sql-data:
    name: sql-data
    driver: local

networks:
  default:
    name: ssmc_network
